spring.datasource.url=jdbc:postgresql://localhost:5432/db_hospital
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

jwt.secret=chave-secreta-so-para-testar-1234567890
jwt.expiration=160000
jwt.issuer=projeto-hospital

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug