spring.application.name=hospital-asset-management

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.envers.store_data_at_deletion=true
spring.jackson.time-zone=America/Sao_Paulo
logging.level.org.springframework.security=DEBUG
server.port=${PORT:8080}

springdoc.api-docs.resolve-hateoas=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html