spring.application.name=projeto-hospital

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.envers.store_data_at_deletion=true

spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.queries=trace
spring.profiles.active=prod

server.port=${PORT:8080}

